/* automatically generated by rust-bindgen 0.61.0 */

extern "C" {
    pub fn add(a: ::std::os::raw::c_int, b: ::std::os::raw::c_int);
}
extern "C" {
    pub fn multiply(a: ::std::os::raw::c_int, b: ::std::os::raw::c_int);
}
