[package]
name = "sha256digest-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name="sha256digest"
create-type=["staticlib"]

[dependencies]
ring = "0.16"

