[package]
name = "project"
version = "0.1.0"
edition = "2021"
authors = ["yango <fake.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[dev-dependencies]


[workspace]
